### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by arun1595** [strawberrycanyon/redeemify#12]
Based on the dicussion from https://github.com/strawberrycanyon/redeemify/pull/11, we need to setup Travis CI on the repo.

**Comment by mattlindsey** [comment]
I'll work on this.  I have requested (in Slack) from Sam Joseph that I be added to the github 'strawberrycanyon' organization so that I can configure this repository to submit to Travis.

I think I will also setup a 'strawberrycanyon' team on Heroku (https://devcenter.heroku.com/articles/heroku-teams) that will include admins allowed to submit staging or production builds, etc.   
After everything is working, I will transfer ownership of the team to the 'strawberrycanyon' organization or Armando himself.

**Comment by mattlindsey** [comment]
Successfully deploying to Update.  I successfully deployed to http://redeemify-staging.herokuapp.com/.

Closing this issue.
