### ISSUE TITLE
Need to secure the secrets

### ISSUE THREAD

**Issue by armandofox** [strawberrycanyon/redeemify#8]
1. remove application.yml from version control
2. create (StrawberryCanyon-owned) keys and add them to config/application.yml
3. choose a symmetric keyphrase K to encrypt that file to config/application.yml.asc with `gpg -a -c`
4. checkin config/application.yml.asc
5. run `figaro heroku:set -e production` to set the config vars as ENV variables on Heroku
6. on Travis, set the value of K as an envariable named DECRYPT_KEY
7. add a `before_install` step to travis.yml of the form: `echo $DECRYPT_KEY | gpg -d config/application.yml.asc > config/application.yml`
8. Make sure the app's developers/deployers (but nobody else) knows the value of K

**Comment by armandofox** [comment]
...see the `README.md` file for AgileVentures/projectscope_mvp for a more detailed description of how to do this

**Comment by mattlindsey** [comment]
This task is mostly done, and the app is successfully deployed to http://redeemify-staging.herokuapp.com/.

But I had to add SECRET_KEY_BASE to config/initializers/secret_token.rb.
This should preferably be moved to the encrypted application.yml file, and the secret_token.rb file should not be used.

**Comment by mattlindsey** [comment]
Note that I found a problem with the "FACEBOOK_KEY:" value in application.yml.  
Since this key is all numbers the value must be given in single quotes like *FACEBOOK_KEY:    '12345'*.   Otherwise the *figaro heroku:set -e production -a redeemify-staging* command fails.

This needs to be corrected in application.yml, and the encrypted file checked back in.

**Comment by mattlindsey** [comment]
application.yml has been updated and all secrets are encrypted in it.  This issue can be closed now.
